# Generated by Django 3.2 on 2021-04-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0003_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='佚名', max_length=20, verbose_name='作者')),
                ('picture', models.ImageField(upload_to='', verbose_name='图片')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('loves', models.IntegerField(default=0, verbose_name='喜爱量')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片标签')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Sueedの小窝，记录生活瞬息，分享学习心得', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
            options={
                'verbose_name': '图片标签',
                'verbose_name_plural': '图片标签',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='游戏名称')),
                ('uid', models.IntegerField(verbose_name='UID')),
                ('photo', models.ImageField(upload_to='', verbose_name='游戏信息截图')),
            ],
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.AlterModelOptions(
            name='bigcategory',
            options={'verbose_name': '一级分类', 'verbose_name_plural': '一级分类'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '二级分类', 'verbose_name_plural': '二级分类'},
        ),
        migrations.AlterField(
            model_name='bigcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='bigcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueed.bigcategory', verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='二级分类'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sueed.albumtag', verbose_name='图片标签'),
        ),
    ]
