# Generated by Django 3.2 on 2021-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0004_auto_20210417_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumtag',
            old_name='create_date',
            new_name='update_date',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='好康', max_length=20, verbose_name='图片名称'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(to='sueed.AlbumTag', verbose_name='图片标签'),
        ),
    ]
