# Generated by Django 3.2 on 2021-04-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0006_auto_20210419_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_picture_title',
            field=models.BooleanField(default=False, verbose_name='是否为头版背景'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='无授权转载分享，请勿商用，侵删', max_length=20, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='album/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='albumtag',
            name='surface',
            field=models.ImageField(default='default.jpg', upload_to='album/surface/', verbose_name='封面'),
        ),
    ]
