# Generated by Django 3.2 on 2021-04-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0007_auto_20210421_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_vertical',
            field=models.BooleanField(default=False, verbose_name='是否竖向图片'),
        ),
    ]
