# Generated by Django 3.2 on 2021-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0008_album_is_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_vertical',
        ),
        migrations.AddField(
            model_name='album',
            name='title_tag',
            field=models.CharField(default='', max_length=10, verbose_name='头版背景标签'),
        ),
    ]
