# Generated by Django 3.2 on 2021-04-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0009_auto_20210423_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_link',
            field=models.CharField(default=models.CharField(default='surface.jpg', max_length=50, verbose_name='文章图片'), max_length=255, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=700, verbose_name='文章摘要'),
        ),
    ]
