# Generated by Django 3.2 on 2021-04-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0010_auto_20210425_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='surface',
            field=models.CharField(default='surface.jpg', max_length=50, verbose_name='文章图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='surface.jpg', max_length=255, verbose_name='图片地址'),
        ),
    ]
