# Generated by Django 3.2 on 2021-04-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0011_auto_20210425_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='surface',
        ),
    ]
