# Generated by Django 3.2 on 2021-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sueed', '0012_remove_article_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='series_name',
            field=models.CharField(default='none', max_length=20, verbose_name='系列名称'),
        ),
    ]
